model:
  device: "cpu"
  paths:
    cache_dir: "results/cache/bert_int"
    dataset_root: null
    description_dict: null
    model_save_dir: "results/bert_int/basic_unit"
    model_save_prefix: "run"

  basic_unit:
    encoder_name: "bert-base-multilingual-cased"
    encoder_strategy: "auto"
    max_seq_length: 128
    dropout: 0.1
    model_input_dim: 768
    learning_rate: 1.0e-5
    load_pretrained: true
    negatives_per_positive: 2
    margin: 3.0
    eval_batch_size: 128
    result_size: 300
    dataset:
      name: null
      fold: null

  interaction:
    batch_size: 64
    cosine_top_k: 50
    temperature: 0.1

  seed:
    global: 42
